// filename: apps/supabase/functions/import-user-games/index.ts
import "jsr:@supabase/functions-js/edge-runtime.d.ts";

// Read the WASM file
import {
  get_chess_games,
  get_combined_chess_games,
} from "@chess_pgn_retriever";

/**
 * Processes PGN data to extract game information
 * @param {Uint8Array} pgnData - Raw PGN data
 * @returns {any} - Processed game data
 */
function processPgnData(pgnData: Uint8Array): any {
  // Convert binary data to string
  const pgnText = new TextDecoder().decode(pgnData);

  // Split into individual games
  const games = pgnText
    .split(/\n\n(?=\[Event)/)
    .filter((game) => game.trim().length > 0);

  // Filter for rapid, blitz, and bullet games
  const filteredGames = games.filter((game) => {
    const timeControlMatch = game.match(/\[TimeControl "(.+?)"\]/);
    if (!timeControlMatch) return false;

    const timeControl = timeControlMatch[1];
    // Parse time control
    const baseTime = parseInt(timeControl.split("+")[0], 10);

    // Bullet: < 3 min, Blitz: 3-10 min, Rapid: > 10 min
    return baseTime < 180 || (baseTime >= 180 && baseTime <= 600) ||
      baseTime > 600;
  });

  return {
    total: games.length,
    filtered: filteredGames.length,
    games: filteredGames.join("\n\n"),
  };
}

Deno.serve(async (req) => {
  console.log("Received request:", req.url);
  // Parse the request body if this is a POST request
  let username = "ekhar02"; // Default username

  if (req.method === "POST") {
    const requestText = await req.text();
    // If body is not empty, use it as username
    if (requestText.trim().length > 0) {
      username = requestText.trim();
    }
  } else if (req.method === "GET") {
    // Check for username in query params
    const url = new URL(req.url);
    const queryUsername = url.searchParams.get("username");
    if (queryUsername) {
      username = queryUsername;
    }
  }

  console.log(`Importing games for ${username}`);

  // Get current year and month
  const now = new Date();
  const currentYear = now.getFullYear();
  const currentMonth = now.getMonth() + 1; // JavaScript months are 0-indexed

  // Fetch the last 3 months of games using the WASM module
  console.log(`Fetching games for ${username} for the last 3 months`);

  // Use the WASM function to fetch combined games
  // Note: In real implementation, you would use the actual binding generated by wasm-bindgen
  const combinedPgn = await get_combined_chess_games(
    username,
    currentYear,
    currentMonth,
    3, // Number of months to fetch
  );

  // Process the combined PGN data
  const processedData = processPgnData(combinedPgn);

  // Calculate the months that were fetched (for reporting)
  const monthsToFetch = [];
  for (let i = 0; i < 3; i++) {
    let month = currentMonth - i;
    let year = currentYear;

    if (month <= 0) {
      month += 12;
      year -= 1;
    }

    monthsToFetch.push({ year, month });
  }

  // For download request, return the PGN file
  const url = new URL(req.url);
  if (url.searchParams.get("download") === "true") {
    return new Response(processedData.games, {
      headers: {
        "Content-Type": "application/x-chess-pgn",
        "Content-Disposition":
          `attachment; filename="ChessCom_${username}_filtered.pgn"`,
      },
    });
  }

  // Otherwise return JSON response
  return new Response(
    JSON.stringify(
      {
        username,
        total_games: processedData.total,
        filtered_games: processedData.filtered,
        months_fetched: monthsToFetch,
      },
      null,
      2,
    ),
    { headers: { "Content-Type": "application/json" } },
  );
});

/* To invoke locally:

  1. Run `supabase start` (see: https://supabase.com/docs/reference/cli/supabase-start)
  2. Make an HTTP request:

  // GET request with username as query parameter
  curl -i --location --request GET 'http://127.0.0.1:54321/functions/v1/import-user-games?username=ekhar02' \
    --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0'

  // POST request with username in the body
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/import-user-games' \
    --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0' \
    --header 'Content-Type: text/plain' \
    --data 'ekhar02'

  // Download the PGN file
  curl -i --location --request GET 'http://127.0.0.1:54321/functions/v1/import-user-games?username=ekhar02&download=true' \
    --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0' \
    --output 'chess_games.pgn'

*/
