[package]
name = "chess-compression"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[toolchain]
channel = "stable"
components = ["rustfmt", "clippy"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
shakmaty = "0.27"
thiserror = "2.0"
bit-vec = "0.6.3"
huffman-compress = "0.6.1"
wasm-bindgen = "0.2.84"
console_error_panic_hook = { version = "0.1.7", optional = true }
js-sys = "0.3.70"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
strip = true
